#!/usr/bin/env bash
# Writes firebase-config.js from FIREBASE_API_KEY, read from .env locally or from the environment in GitHub Actions.
set -euo pipefail
cd "$(dirname "$0")/.."
if [ -f .env ]; then set -a; . ./.env; set +a; fi
: "${FIREBASE_API_KEY:?Set FIREBASE_API_KEY in .env (local) or as a GitHub Actions secret}"
cat > firebase-config.js <<CONFIG
// Generated by scripts/make-config.sh — do not commit.
window.FIREBASE_CONFIG = {
  apiKey: "${FIREBASE_API_KEY}",
  authDomain: "house-chores-e9115.firebaseapp.com",
  projectId: "house-chores-e9115",
  storageBucket: "house-chores-e9115.firebasestorage.app",
  messagingSenderId: "981849425898",
  appId: "1:981849425898:web:85e2816821bddb2b5f9493"
};
CONFIG
echo "Wrote firebase-config.js"
